s = """
['NOTIFICATIONS_SYSTEM', 'NOTIFICATIONS_TODOLIST', 'NOTIFICATIONS_TIMER', 'NOTIFICATIONS_CHATBOT', 'TIMER_WORK_SESSION_LENGTH', 'TIMER_SHORT_BREAK_SESSION_LENGTH', 'TIMER_LONG_BREAK_SESSION_LENGTH', 'TIMER_INTERVAL']
"""


r = s.replace("'", '"')
print(r)