"""Updated user table

Revision ID: 009600b2f8da
Revises: c7c8d01e92b6
Create Date: 2023-06-30 19:18:15.978369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009600b2f8da'
down_revision = 'c7c8d01e92b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
