"""Initial migration

Revision ID: c695380cee0f
Revises: 493a68c91fd6
Create Date: 2023-05-30 21:45:30.218633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c695380cee0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('timer_session_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer_session_count',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=32), nullable=False),
    sa.Column('session_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('attr', sa.VARCHAR(length=32), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attr')
    )
    # ### end Alembic commands ###
