"""Added column to chatbot table

Revision ID: c7c8d01e92b6
Revises: c695380cee0f
Create Date: 2023-06-04 21:33:45.818399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c8d01e92b6'
down_revision = 'c695380cee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=8), nullable=False))
        batch_op.drop_index('ix_chatbot_message_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.create_index('ix_chatbot_message_value', ['value'], unique=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
